### PR TITLE
Styling tweaks

### LINKED ISSUE #49: Docs look and feel update (light and dark)
Bring the docusauras color scheme into alignment with other stateful stuff.

Stateful_Runme_Doc_dark
Stateful_Runme_Docs light

### PR DESCRIPTION
**Pull request by christian-bromann**
fixes #49

Summary Navigation:

- adjusted underline color and size
- increased gap size
- aligned frontpage nav and docs nav

Summary frontpage:

- moved `Learn about v1.0 roadmap and 🔥 new features` below intro image
- adjusted `runme` search query in hero according to design
- size and position improvements to OSS section
- fix responsive design issues in "Documentation" section

Summary docs:
- adjusted style of code blocks in text
- removed horizontal scrolling in paragraph code blocks
- added "On this page" heading to sub navi
- adjusted background color

### CODE REVIEW

**Comment by admc** [comment]
Looking good, can you also take a swing at tightening up the space in the CTA at the bottom of the page?

**Comment by christian-bromann** [comment]
> Looking good, can you also take a swing at tightening up the space in the CTA at the bottom of the page?

Done

**Comment by admc** [comment]
Just this:

image

**Comment by christian-bromann** [comment]
> Oh this had visual tweeks too:

Done

> Just this:

Done

**Review by admc — APPROVED** [review]
👍

**Pull request merged**
