### PR TITLE
Add test pipeline for Deno unit tests

### LINKED ISSUE #40: Run tests continuously: pre-commit hook?
While https://github.com/stateful/runme.dev/issues/29 helped with general brittleness, I do find it outdated quite regularly when I run through the README steps as part of general testing.

### PR DESCRIPTION
**Pull request by christian-bromann**
fixes #40

### CODE REVIEW

**Comment by christian-bromann** [comment]
This will make sure we have some tests. Component testing in Deno is not well supported yet. Our current solution is already very hacky.

**Review by sourishkrout — APPROVED** [review]
LGTM 👍  assuming the ignored test cases are intentional.

**Comment by christian-bromann** [comment]
> assuming the ignored test cases are intentional.

They don't pass anymore. If you like I can spend more time finding out why but again, component testing with Deno is just not yet well supported.

**Comment by sourishkrout** [comment]
> > assuming the ignored test cases are intentional.
> 
> They don't pass anymore. If you like I can spend more time finding out why but again, component testing with Deno is just not yet well supported.

Feel free to create a follow up ticket. No need to dig deeper right now though. Thank you!

**Pull request merged**
